### ISSUE TITLE
Not able to connect to Trail S4HANA instance from SAP BTP

### ISSUE THREAD

**Issue by nappana** [SAP/cloud-sdk#222] opened 2021-04-14 16:59 UTC
Not able to connect to S4HANA Trail version from SAP BTP.

I have configured destination instance in SAP BTP and provided my S4HANA instance IP with basic authentication in Dashboard of Destination Instance.

### Impact / Priority

Could not run my extension application with trial s4hana instance. In local I am able to connect after giving entry in /etc/host file and exporting the certificate to JDK.

## Error Message

Failure reason: "An error of type SSLHandshake occurred during check connection!"

## Project Details

- SAP Cloud SDK Version: 2.1.2

- Project type, 
  - Spring Boot application with SAP cloud sdk libraries
- Platform:
  - [ ] Cloud Foundry
  

---

**Comment by Emdee89** [comment] 2021-04-15 10:21
Hi @nappana, this issue looks like a duplicate of https://stackoverflow.com/questions/66958435/not-able-to-connect-to-trial-s4instance-in-cal-from-sap-btp-destination-service.

As mentioned on Stackoverflow, you seem to use a pretty outdated version of the SAP Cloud SDK.

We recommend to use the latest version. At the time of this writing, this is SAP Cloud SDK 3.42.0.

Please follow the [release notes](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java) to stay up-to-date.

**Comment by newtork** [comment] 2021-05-05 11:12
Hello @nappana,

I'm closing this issue due to inactivity. Please respond or re-open when there is new information.

Kind regards
Alexander

**Closed by newtork** 2021-05-05 11:12 UTC
Labels: Java
