### ISSUE TITLE
Error message about wrong odata version requires improvement

### ISSUE THREAD

**Issue by uwe-klinger** [SAP/cloud-sdk#888] opened 2022-07-01 07:25 UTC
**Let us know how we can improve**

When requesting a OData service using the wrong OData version, e.g. requesting a OData v2 service as OData v4, the response cannot be parsed and a not understandable error message is logged by the Cloud SDK:

```
OData response cannot be read as set of entities
```

I tried to increase the log level, but the Cloud SDK doesn't reveal further hints.

It would be helpful if the situation could be detected and the error message could be more precise, or at least the reason why the response cannot be parsed (= what's wrong with it) is outputed.

**Comment by MatKuhr** [comment] 2022-07-01 08:19
Hi Uwe,

thanks for pointing this out! The OData client currently does not have a means to detect if an OData service is responding based on a different OData version than the call was made with. AFAIK such a check would require an additional metadata request. I think the main use case of the SDK is using a generated client, and that should prevent such a mismatch in the first place. [This is why we advice to generally use the type-safe, generated client if possible.](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client)

But I assume you are using the client directly? Could you share the stack trace of your call?

Generally, to get more information on parsing problems we have [more specific error types](https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v2-client-in-sap-cloud-sdk-for-java#error-handling) that give access to the response data. We also have some log messages for malformed response content that give more information, but I guess those were not hit in this case. I'll check if we can improve that, but I am afraid this is not easy to do since the code is accounting for various different V2 and V4 formats.

**Comment by uwe-klinger** [comment] 2022-07-04 05:36
Hi Matthias,

The Cloud SDK is used through CAP. The use of the type-safe, generated client is not possible there. For CAP, this is a misconfiguration that can easily happen. I think the outer object is different in OData v2 and v4. Maybe this can be checked.

We will check if we can take more information from the specific error types that you've mentioned. 

Thanks,
Uwe

**Comment by beckermarc** [comment] 2022-07-04 06:59
Do you think it would be useful to provide the original exception that might have occurred during deserialization in the cause, so you can see it in the stacktrace? Or doesn't [your code](https://github.wdf.sap.corp/MA/sdk/blob/ab080b1fbe4787a11d476bb7d79bb9e545d1947f/datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultGeneric.java#L338) throw on deserialization issues?

**Comment by MatKuhr** [comment] 2022-07-04 07:10
Yes, I think throwing an exception on the higher-level is a good idea here. In this particular case the code doesn't throw, because the json object we look for doesn't exist (at least that is my guess what happens). So we just get null. In other cases we will also throw more specific errors, e.g. if parsing data into a POJO failed.

We could print out more information about which JSON structure was expected vs. what we actually got. But I think this is difficult to do in the code since we handle numerous different formats and the code is quite generic to deal with that. Also, I'm not sure how much this would really help in your case, since the expected format is already wrong.

**Comment by beckermarc** [comment] 2022-07-04 07:18
A minor improvement (that would have helped in our case to better understand the error) would be to print information about the deserializer that was used in the error message. As you also mention yourself that you handle "numerous different formats" I think this is a reasonable change. In our case this would have shown us that the response was interpreted as OData V4, while we knew that we are accessing an V2 API.

**Comment by Johannes-Schneider** [comment] 2022-08-11 14:40
Hi @beckermarc and @uwe-klinger,

did you find some time to check whether our new exception message improved the situation for you?
And, if so, could you please close this incident?

Thanks and best regards,
Johannes

**Comment by beckermarc** [comment] 2022-08-11 14:49
I just tried it out. The error message `Unable to read OData 4.0 response.` is now more helpful. Thanks. You can close this issue (I can't)

**Closed** 2022-08-11 18:43 UTC
Labels: feedback
