### ISSUE TITLE
Extending SaaS solution not able to cds login

### ISSUE THREAD

**Issue by denis1989java** [SAP/cloud-sdk#1043] opened 2022-10-05 08:31 UTC
Hello colleagues,

We have multi-tenancy CAP java application. 
<img width="637" alt="Screenshot 2022-10-05 at 11 15 40" src="https://user-images.githubusercontent.com/29613632/194014220-69a45985-dfc1-468e-9f7b-64294260fa85.png">

We need implement next flow:
<img width="587" alt="Screenshot 2022-10-05 at 11 16 00" src="https://user-images.githubusercontent.com/29613632/194014336-036b342e-60db-400f-82a6-b6b8e4e14f4b.png">

I'm trying to achieve Extensibility(updating specific cds for specific tenant.

I'm following current guide https://cap.cloud.sap/docs/guides/extensibility/customization and failing on first step cds login. It's throwing 401 no matter how I'm trying to login.
<img width="926" alt="Screenshot 2022-10-05 at 11 23 06" src="https://user-images.githubusercontent.com/29613632/194017253-91445fb9-44f8-4151-a93d-e29864b8487c.png">

We have multitenancy app. With multiple consumers where I need to update specific cds (metadata) for specific tenant. I've used provider url and tried others. 

1. What I'm doing wrong in first step, cds login. Do we need make some changes on backend to get correct app_url? 
2. Do you have any example of  multitenancy  app. With java or atleast node.js?
3. Are extend and activate methods exist in java sdk? Or we need create node js application? Because by our flow customer will just call endpoint on provider backend application.

Feel free connect me in teams dzianis.monich@sap.com

Best regards,
Dzianis Monich

**Comment by Johannes-Schneider** [comment] 2022-10-05 09:20
For transparency: 
I talked to Dzianis privately and suggested to reach out to the CAP colleagues as the issue doesn't seem to be related to the Cloud SDK.

I'd therefore close the issue for now.
Please feel free to either re-open this incident or to create a new one in case the issue is actually related to the SAP Cloud SDK.

**Closed by Johannes-Schneider** 2022-10-05 09:20 UTC
