### ISSUE TITLE
[Java] Feedback: The Testutil Modules are valuable and should not be removed

### ISSUE THREAD

**Issue by Johannes-Schneider** [SAP/cloud-sdk#818] opened 2022-05-18 08:16 UTC
## Ask for feedback

This issue is meant to collect user feedback regarding the upcoming removal of the `testutil-*` modules from the public deliveries of the SAP Cloud SDK for Java.

### Following modules **wont't** be available after the release of version 4:
- [testutil-parent](https://search.maven.org/search?q=g:com.sap.cloud.sdk.testutil%2BAND%2Ba:testutil-parent) (`com.sap.cloud.sdk.testutil:testutil-parent`)
- [testutil-core](https://search.maven.org/search?q=g:com.sap.cloud.sdk.testutil%2BAND%2Ba:testutil-parent) (`com.sap.cloud.sdk.testutil:testutil-core`)
- [testutil-resources](https://search.maven.org/search?q=g:com.sap.cloud.sdk.testutil%2BAND%2Ba:testutil-parent) (`com.sap.cloud.sdk.testutil:testutil-resources`)

### If you are relying on (one of) these modules, please react with a 👍 to let us know

**Comment by Johannes-Schneider** [comment] 2022-05-18 11:20
Removing these modules will impact the Cloud SDK tutorials.
For example: https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html#30540988-5d47-4e9a-a6d3-9ea8dcd23cfc

**Comment by theits** [comment] 2022-07-13 16:28
> Hi @zerbarus and @theits, Can you please explain the usage of `testutil-*` in your project? Maybe we can propose a different API call that matches your use-case.

Hi @newtork ,

I am using com.sap.cloud.sdk.testutil.MockUtil in order to mock the destination-service from the cloud foundry environment for integration testing.

**Comment by newtork** [comment] 2022-07-15 18:30
Hi @theits
Can you consider the following usage instead...?

```java
@Before
public void setLoader() {
  final DefaultHttpDestination dest = DefaultHttpDestination.builder("http://destination/").name("MyDest").build();
  final DefaultDestinationLoader loader = new DefaultDestinationLoader().registerDestination(dest);
  DestinationAccessor.setLoader(loader);
}

@After
public void resetLoader() {
  DestinationAccessor.setLoader(null);
}
```

Benefits:
* No mocking necessary.
* No additional testutil dependency.
* API is "more stable" than testutil code.

Of course there are semantic differences, please let me know, if it's missing something.

**Comment by theits** [comment] 2022-07-19 06:51
Hi @newtork ,
Thanks for your response, your solution works great for my usecase. The only drawback is, that DefaultDestinationLoader is annotated with `@Beta`. I hope it stays stable.

**Comment by MatKuhr** [comment] 2024-02-19 12:27
Closing this as `MockUtil` has been removed

**Closed by MatKuhr** 2024-02-19 12:27 UTC
Labels: Java, feedback

**Comment by sap-manaschuri** [comment] 2024-02-24 06:20
We are migrating the com.sap.cloud.sdk:sdk-modules-bom from 4.27.0 to 5.2.0 and trying to remove the dependency of com.sap.cloud.sdk.cloudplatform:scp-cf and com.sap.cloud.sdk.testutil:testutil-core as it is depricated.
When we used following code instead of MockDestination and MockUtil

@Before
public void setLoader() {
  final DefaultHttpDestination dest = DefaultHttpDestination.builder("http://destination/").name("MyDest").build();
  final DefaultDestinationLoader loader = new DefaultDestinationLoader().registerDestination(dest);
  DestinationAccessor.setLoader(loader);
}

We are getting following error :

Caused by: java.lang.ClassNotFoundException: com.sap.cloud.sdk.cloudplatform.security.secret.exception.KeyStoreAccessException

Can you please suggest the solution?
Thanks,
Manas
